In [ ]:
import numpy as np

#### Q1. Create a NumPy array containing integers from 0 to 9.

In [4]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [7]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

#### Q3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [10]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [11]:
arr = np.random.randint(1,100, size=(5,4))
arr

array([[60, 43, 28, 56],
       [ 6, 17, 87, 91],
       [55, 23, 51, 35],
       [81, 41, 67, 19],
       [13, 87, 42, 93]], dtype=int32)

#### Q5. Create a 3x3 array of integers and access:

In [28]:
arr1 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

#### a. The second element of the first row.

In [29]:
arr1[0, 1]

np.int64(20)

#### b. The third column of the 2nd row.

In [32]:
arr1[1,2]

np.int64(60)

#### c. A subarray with the first two rows and last two columns.

In [33]:
arr1[0:2, 1:3]

array([[20, 30],
       [50, 60]])

#### Q6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [34]:
arr2 = np.arange(12)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
arr2 = arr2.reshape(3,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Q7. Reshape a 3x3 matrix into a 1D array.

In [10]:
arr1 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
arr1 = arr1.reshape(-1)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

### Q3.Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition, subtraction, multiplication, and division on them.

In [18]:
arr1 = np.array([[10,20,30],
                [40,50,60]])

arr2 = np.array([[15,18,10],
                [20,10,40]])

In [19]:
arr1

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
arr2

array([[15, 18, 10],
       [20, 10, 40]])

In [29]:
add = arr1 + arr2
add

array([[0.66666667, 1.11111111, 3.        ],
       [2.        , 5.        , 1.5       ]])

In [31]:
sub = arr1 - arr2
sub

array([[-5,  2, 20],
       [20, 40, 20]])

In [32]:
mul = arr1 * arr2
mul

array([[ 150,  360,  300],
       [ 800,  500, 2400]])

In [33]:
div = arr1 / arr2
div

array([[0.66666667, 1.11111111, 3.        ],
       [2.        , 5.        , 1.5       ]])

### Q9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [34]:
arr = np.array([1,2,3,4,5])

In [36]:
total_sum = np.sum(arr)
total_sum

np.int64(15)

In [37]:
mean = np.mean(arr)
mean

np.float64(3.0)

In [39]:
stand_deviation = np.std(arr)
stand_deviation

np.float64(1.4142135623730951)

### Q10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

In [40]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

In [48]:
result_dot = np.dot(A,B)
result_dot

array([[19, 22],
       [43, 50]])

In [47]:
result_at = A @ B
result_at

array([[19, 22],
       [43, 50]])

### Q11. Find the transpose of matrix A and matrix B.

In [49]:
A_T = A.T
A_T

array([[1, 3],
       [2, 4]])

In [50]:
B_T = B.T
B_T

array([[5, 7],
       [6, 8]])

### Q12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [55]:
arr1d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
arr1d

In [57]:
arr2d = np.array([10,20,30])
arr2d

array([10, 20, 30])

In [58]:
result = arr2d + arr1d
result

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

### Q13.Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.

In [61]:
arr = np.random.randint(1, 100 , size=(4,4))
arr

array([[40, 72, 95, 26],
       [22, 97, 25, 28],
       [19, 69, 82, 73],
       [56, 28, 96, 24]], dtype=int32)

In [65]:
min = np.min(arr)
min

np.int32(19)

In [67]:
max = np.max(arr)
max

np.int32(97)

In [68]:
mean = np.mean(arr)
mean

np.float64(53.25)

### Q14.Find the row-wise and column-wise sums.

In [69]:
row_sum = np.sum(arr, axis=1)
row_sum

array([233, 172, 243, 204])

In [70]:
clm_sum = np.sum(arr, axis=0)
clm_sum

array([137, 266, 298, 151])

### 15. Generate an array of 10 random integers between 1 and 50.

In [71]:
random_int = np.random.randint(1,51, size=10)
random_int

array([ 8, 35, 47, 12, 49, 25, 22, 21, 39,  9], dtype=int32)

### 16. Generate a 5x5 matrix of random floats between 0 and 1.

In [72]:
rand_float = np.random.rand(5,5)
rand_float

array([[0.47356485, 0.44644473, 0.55377164, 0.66446759, 0.08420952],
       [0.16762044, 0.45711503, 0.24398802, 0.20111599, 0.49867471],
       [0.42571184, 0.14306165, 0.13743792, 0.91477108, 0.87336377],
       [0.75357601, 0.71555607, 0.2176648 , 0.87631602, 0.24320152],
       [0.09179049, 0.38379904, 0.60192902, 0.31205868, 0.6103649 ]])